//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordleSolver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordleSolver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a,98
        ///aardvark,96
        ///aardwolf,21
        ///abaca,24
        ///aback,86
        ///abacus,93
        ///abaft,19
        ///abalone,69
        ///abandon,100
        ///abandoned,100
        ///abandonee,66
        ///abandoner,86
        ///abandonment,99
        ///abase,75
        ///abased,79
        ///abasement,81
        ///abash,89
        ///abashed,94
        ///abashedly,86
        ///abashment,79
        ///abatable,72
        ///abate,93
        ///abatement,89
        ///abattoir,59
        ///abbacy,19
        ///abbatial,19
        ///abbe,19
        ///abbess,52
        ///abbey,95
        ///abbot,81
        ///abbotship,42
        ///abbreviate,99
        ///abbreviated,99
        ///abbreviation,100
        ///abbreviator,91
        ///abdicable,44
        ///abdicant,64
        ///abdicate,91
        ///abdication,90
        ///abdicative,65
        ///abdicat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnglishDictionary {
            get {
                return ResourceManager.GetString("EnglishDictionary", resourceCulture);
            }
        }
    }
}
